version: '2'
services:
  membersrvc:
    image: hyperledger/fabric-membersrvc:x86_64-0.6.1-preview
    ports:
      - "7054:7054"
    command: membersrvc

  vp0:
    image: hyperledger/fabric-peer:x86_64-0.6.1-preview
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "7050:7050"
      - "7051:7051"
    environment:
      - CORE_PEER_ID=vp0
      - CORE_SECURITY_ENROLLID=test_vp0
      - CORE_SECURITY_ENROLLSECRET=MwYpmSRjupbT

      - CORE_PEER_DISCOVERY_PERIOD=5s
      - CORE_PEER_DISCOVERY_TOUCHPERIOD=6s
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_VM_ENDPOINT=unix:///var/run/docker.sock
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_PKI_ECA_PADDR=membersrvc:7054
      - CORE_PEER_PKI_TCA_PADDR=membersrvc:7054
      - CORE_PEER_PKI_TLSCA_PADDR=membersrvc:7054
#      - CORE_SECURITY_ENABLED=true
#      - CORE_SECURITY_PRIVACY=true
      - CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN=pbft
      - CORE_PBFT_GENERAL_MODE=batch
      - CORE_PBFT_GENERAL_N=4
    links:
    - membersrvc
    command: sh -c "sleep 5; peer node start"

  vp1:
    image: hyperledger/fabric-peer:x86_64-0.6.1-preview
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "7052:7052"
    environment:
      - CORE_PEER_DISCOVERY_ROOTNODE=vp0:7051
      - CORE_PEER_ID=vp1
      - CORE_SECURITY_ENROLLID=test_vp1
      - CORE_SECURITY_ENROLLSECRET=5wgHK9qqYaPy

      - CORE_PEER_DISCOVERY_PERIOD=5s
      - CORE_PEER_DISCOVERY_TOUCHPERIOD=6s
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_VM_ENDPOINT=unix:///var/run/docker.sock
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_PKI_ECA_PADDR=membersrvc:7054
      - CORE_PEER_PKI_TCA_PADDR=membersrvc:7054
      - CORE_PEER_PKI_TLSCA_PADDR=membersrvc:7054
#      - CORE_SECURITY_ENABLED=true
#      - CORE_SECURITY_PRIVACY=true
      - CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN=pbft
      - CORE_PBFT_GENERAL_MODE=batch
      - CORE_PBFT_GENERAL_N=4
    links:
      - membersrvc
      - vp0
    command: sh -c "sleep 10; peer node start"

  vp2:
    image: hyperledger/fabric-peer:x86_64-0.6.1-preview
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "7053:7053"
    environment:
      - CORE_PEER_DISCOVERY_ROOTNODE=vp0:7051
      - CORE_PEER_ID=vp2
      - CORE_SECURITY_ENROLLID=test_vp2
      - CORE_SECURITY_ENROLLSECRET=vQelbRvja7cJ

      - CORE_PEER_DISCOVERY_PERIOD=5s
      - CORE_PEER_DISCOVERY_TOUCHPERIOD=61s
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_VM_ENDPOINT=unix:///var/run/docker.sock
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_PKI_ECA_PADDR=membersrvc:7054
      - CORE_PEER_PKI_TCA_PADDR=membersrvc:7054
      - CORE_PEER_PKI_TLSCA_PADDR=membersrvc:7054
#      - CORE_SECURITY_ENABLED=true
#      - CORE_SECURITY_PRIVACY=true
      - CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN=pbft
      - CORE_PBFT_GENERAL_MODE=batch
      - CORE_PBFT_GENERAL_N=4
    links:
      - membersrvc
      - vp0
    command: sh -c "sleep 15; peer node start"

  vp3:
      image: hyperledger/fabric-peer:x86_64-0.6.1-preview
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      ports:
        - "7056:7056"
      environment:
        - CORE_PEER_DISCOVERY_ROOTNODE=vp0:7051
        - CORE_PEER_ID=vp3
        - CORE_SECURITY_ENROLLID=test_vp3
        - CORE_SECURITY_ENROLLSECRET=9LKqKH5peurL

        - CORE_PEER_DISCOVERY_PERIOD=60s
        - CORE_PEER_DISCOVERY_TOUCHPERIOD=61s
        - CORE_PEER_ADDRESSAUTODETECT=true
        - CORE_VM_ENDPOINT=unix:///var/run/docker.sock
        - CORE_LOGGING_LEVEL=INFO
        - CORE_PEER_PKI_ECA_PADDR=membersrvc:7054
        - CORE_PEER_PKI_TCA_PADDR=membersrvc:7054
        - CORE_PEER_PKI_TLSCA_PADDR=membersrvc:7054
#        - CORE_SECURITY_ENABLED=true
#        - CORE_SECURITY_PRIVACY=true
        - CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN=pbft
        - CORE_PBFT_GENERAL_MODE=batch
        - CORE_PBFT_GENERAL_N=4
      links:
        - membersrvc
        - vp0
      command: sh -c "sleep 20; peer node start"

